config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :restaurants, only: [ :index, :show ] do
    resources :reviews, only: :create
  end

  resources :restaurants, only: [] do
    patch :mark_as_favorite, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all.order(:name)
    @restaurant_count = Restaurant.count
    respond_to do |format|
      format.html
      format.json { render json: { restaurants: @restaurants }}
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def mark_as_favorite # toggle_favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.toggle(:favorite)
    @restaurant.save!
    respond_to do |format|
      format.html
      format.js do
        render partial: "favorite", locals: { restaurant: @restaurant }
        # @restaurant.toggle(:favorite)
        # @restaurant.save!
      end
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxInRailsTuto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/_card.html.erb
<div class="card-product m-3">
  <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" %>
  <div class="card-product-infos">
    <div class="d-flex align-items-center">
      <%= link_to restaurant_path(restaurant), class: "card-link" do %>
        <h2><%= restaurant.name %></h2>
      <% end %>

      <%= link_to mark_as_favorite_restaurant_path(restaurant), method: :patch,
                                                                class: "ml-2 favorite",
                                                                data: {
                                                                  controller: "favorite",
                                                                  favorite_target: "star",
                                                                  favorite_restaurant_id_value: "#{restaurant.id}",
                                                                  action: "click->favorite#updateStar"
                                                                } do %>
        <%= render "favorite", restaurant: restaurant %>
      <% end %>
    </div>

    <p><%= restaurant.address %></p>
  </div>
</div>

app/views/restaurants/_favorite.html.erb
<% if restaurant.favorite %>
  <i class="fas fa-star"></i>
<% else %>
  <i class="far fa-star"></i>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div class="flex-center mt-4" data-controller="counter">
  <div class="counter">
    <span data-counter-target="count"><%= @restaurant_count %></span>
  </div>

  <button class="btn btn-outline-secondary"
          data-action="click->counter#refresh">
    Refresh counter
  </button>
</div>

<div>
  <% @restaurants.each do |restaurant| %>
    <%= render "card", restaurant: restaurant %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> <small><%= @restaurant.address %></small></h1>

<h2>
  <%= pluralize @restaurant.reviews.size, "review" %>
</h2>

<div id="reviews">
  <% if @restaurant.reviews.blank? %>
    Be the first to leave a review for <%= @restaurant.name %>
  <% else %>
    <% @restaurant.reviews.each do |review| %>
      <p><%= review.content %></p>
    <% end %>
  <% end %>
</div>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit %>
<% end %>